# Generated by Django 3.1 on 2020-09-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_staff_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile',
        ),
    ]
