# Generated by Django 3.0.5 on 2020-09-16 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('category', models.CharField(choices=[('open', 'OPEN'), ('obc', 'OBC'), ('ews', 'EWS'), ('sebc', 'SEBC'), ('sc', 'SC'), ('st', 'ST'), ('sbc', 'SBC')], default='OPEN', max_length=6)),
                ('Class', models.CharField(choices=[('sy', 'SY'), ('ty', 'TY'), ('b tech', 'Btech')], default='SY', max_length=6)),
                ('branch', models.CharField(choices=[('ce', 'CE'), ('it', 'IT'), ('cse', 'CSE'), ('prod', 'PROD'), ('me', 'ME'), ('text', 'Text'), ('ee', 'EE')], default='IT', max_length=6)),
                ('addmission_Fees', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
