# Generated by Django 3.0.5 on 2020-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_addmission_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='eid',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
