# Generated by Django 3.1 on 2020-09-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
